/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BattleShip;
import java.util.*;

public class Juego {
	

 Tablero tab = new Tablero(8);
 ArrayList<Barco> barcos = new ArrayList<Barco>();

	
 public Juego()	{
  
  
 
  Barco port1= new Barco (4,"Portaavion One");
  barcos.add(port1);
  Barco port2 = new Barco(4, "Portaavion Two");
  barcos.add(port2);
  Barco  des1 = new Barco (3,"Destructor One");
  barcos.add(des1);
  Barco des2 = new Barco(3, "Destructor Two");
  barcos.add(des2);
  Barco frag1 = new Barco (2,"Fragata One");
  barcos.add(frag1);
  Barco frag2 = new Barco(2, "Fragata Two");
  barcos.add(frag2);
  Barco sub1 = new Barco (1,"Submarino One");
  barcos.add(sub1);
  Barco sub2 = new Barco(1, "Submarino Two");
  barcos.add(sub2);
  
  
  
 }
 public int ComprobarListaBarcos() 
 {
	 return barcos.size();
 }
  
 
  
  public void ColocarBarcos() //falta test de esto
  {
	  

	  int numB = 0;
	  boolean barcoOK = true;
	  Scanner reader = new Scanner(System.in);
	  tab.mostrarTablero();
	  while(numB<8) 
	  {
		
		  System.out.println("Introduce las coordenadas y la posicion del barco"+ (numB+1));
		  System.out.println(barcos.get(numB).getTipo()+" Medida: "+barcos.get(numB).getMedida() );
		  System.out.println("Coordenada X: ");
		  int x = reader.nextInt();
		  System.out.println("Coordenada Y: ");
		  int y = reader.nextInt();
		  System.out.println("Posicion del Barco ( V o H ) ");
		  String pos = reader.next();
		  barcoOK =tab.addBarco(x, y, pos, barcos.get(numB).getMedida(),barcos.get(numB));
		  //guardar posicion en tablero de los barcos asi sabremos si estan tocados o hundidos
		  
		  if(barcoOK == false){
			 System.out.println("Las coordenadas o la posicion del barco incorrectas, sale de los limites del Tablero o posicion ocupada");
		  }else{
			  
			  numB++;
		  }
		 
		
		  tab.mostrarTablero();
	  }
	 
	  reader.close();
	  
	  
	  
  }
  public void Jugar(Jugador jug)  // falta test de esto
  {
	  int tiradas = 0;
	  int totalTiradas= 45;
	  Scanner reader2 = new Scanner(System.in);
	  
	  while(tiradas<totalTiradas) 
	  {
		  System.out.println("EMPIEZA LA TIRADA NUMEROvb"+ (tiradas+1) + " DE "+totalTiradas);
		  System.out.println("INTRODUCE LAS COORDENADAS QUE QUIERAS DISPARAR!");
		  System.out.println("introduce X:");
		  int x = reader2.nextInt();
		  System.out.println("introduce Y:");
		  int y = reader2.nextInt();
		  if((x > 7 || y > 7) || (x<0 || y<0)) 
		  {
			  System.out.println("ERROR!! LAS COORDENADAS DEBEN ESTAR DENTRO DEL TABLERO");
		  }
		  else {
			  
			  boolean tocado = tab.comprobarTirada(x,y);
			  if(tocado == false) 
			  {
				  System.out.println("AGUA!!! NO HAS TOCADO NINGUN BARCO!");
				  
			  }else {
				  
				  int cont=0;
				  boolean encontrado= false;
				  while(cont< barcos.size() && encontrado ==false)
				  {
					  encontrado = barcos.get(cont).comprobarCoordenadas(x,y);
					  if(encontrado== true)
					  {
						  if(barcos.get(cont).estaHundido() == false) 
						  {
							  System.out.println(barcos.get(cont).getTipo()+" TOCADO!!!");
							  jug.sumarTocados();
							  
						  }else {
							  System.out.println(barcos.get(cont).getTipo()+" HUNDIDO!!!");
							  jug.sumarHundidos();

							  
						  }
						 

					  }
					  cont++;
						    
				  }
			  
			  
			  }

			   tiradas++;
			  
		  }
		  
		  
	  }
	  if(jug.numeroHundidos()==8) 
	  {
		  jug.ponerGanador(true);
	  }
	  
	  reader2.close();
  }
  
  
  
  public void DeterminarGanador(Jugador jug1, Jugador jug2) 
  {
	  if(jug1.esGanador()==true && jug2.esGanador()==false) 
	  {
		  System.out.println("EL GANADOR ES EL JUGADOR "+jug1.retNombre()+"!!!!!!");
		  
	  }
	  if(jug2.esGanador()==true && jug1.esGanador()==false) 
	  { System.out.println("EL GANADOR ES EL  "+jug2.retNombre()+"!!!!!");}
	  
	  if(jug2.esGanador()==true && jug1.esGanador()==true)
	  { 
		  
		  if(jug1.numeroHundidos()>jug2.numeroHundidos()) 
		  {
			  System.out.println("EL GANADOR ES EL  "+jug1.retNombre()+"!!!!!!");
			  
		  }
		  if (jug2.numeroHundidos()>jug1.numeroHundidos()){
			  System.out.println("EL GANADOR ES EL  "+jug1.retNombre()+"!!!!!!");
			  
		  }
		  if(jug2.numeroHundidos()==jug1.numeroHundidos())
		  {
			  
			  System.out.println("LOS DOS JUGADORES HABEIS HUNDIDO EL MISMO NUMERO DE BARCOS!!!");
			  if(jug1.numeroTocados()>jug2.numeroTocados()) 
			  {
				  System.out.println("EL GANADOR ES EL "+jug1.retNombre()+"!!!!!!"
				  		+ "PORQUE HA TOCADO MAS BARCOS!!");
				  
			  }
			  if(jug2.numeroTocados()>jug1.numeroTocados()) 
			  {
				  
				  System.out.println("EL GANADOR ES EL :"+jug2.retNombre()+"!!!!!!"
					  		+ "PORQUE HA TOCADO MAS BARCOS!!");
					  
			  }
			  if(jug2.numeroTocados()==jug1.numeroTocados()) {
				  
				  System.out.println("LOS DOS JUGADORES HABEIS TOCADO TAMBIEN EL MISMO NUMERO DE BARCOS!!!");
				  System.out.println("EMPATE TOTAL!!!");
			  }
			  
			  
		  }
		  
	  }
	  
	  
	  
  }
  
  

	
}
