/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BattleShip;

import static org.junit.Assert.*;
import org.junit.Test;

public class JuegoTest {
	    Juego juego = new Juego();
	    
	    @Test
	    public void JuegoCompletoTest() 
	    {
	    	Jugador j1 = new Jugador("j1");
	    	
	    	MockDatosEntrada mck = new MockDatosEntrada();
	    	mck.entradasTeclado(1);
	    	juego.tipoEntradaDatos(mck);
	    	juego.colocarBarcos(); // esto lo hace automaticamente el mock.
	    	mck.entradasTeclado(2); // hay que poner la opcion 2 para que coja los datos de disparar.
	    	juego.jugar(j1); // aki le pasamos el jugador que juega, pero las entradas las mete el mock.
	    	
	    	
	    }
		@Test
		public void ConstructorTest() {
			 
			
			int res1= juego.comprobarListaBarcos();
			assertEquals(res1,8);		
			
		}
		@Test
		public void DeterminarJugador() 
		{
			Jugador j1 = new Jugador("j1");
			Jugador j2 = new Jugador("j2");
			
			j1.ponerGanador(true);
			j2.ponerGanador(false);
			
		//	juego.DeterminarGanador(j1,j2);
			
			j1.ponerGanador(false);
			j2.ponerGanador(true);
			
		//	juego.DeterminarGanador(j1,j2);
			
			j1.ponerGanador(true);
			j2.ponerGanador(true);
			
			j1.sumarTocados();
			j1.sumarTocados();
			j2.sumarTocados();
			
		//	juego.DeterminarGanador(j1,j2);
			
			
			j2.sumarTocados();
			j2.sumarTocados();
			j1.sumarTocados();
			
			
			//juego.DeterminarGanador(j1,j2);
			

			j2.sumarTocados();
			j2.sumarTocados();
			j2.sumarTocados();
			j1.sumarTocados();
			
			juego.determinarGanador(j1,j2);
			
			
		}
		
	
}

